### ISSUE TITLE
Python3でI2Cのセンサを読み取りコンソールに表示

### ISSUE THREAD

**Issue by kantarow** [nanigasi-san/PubSubSensor#1]

**Comment by nanigasi-san** [comment]
lib: https://pypi.org/project/smbus2/

**Comment by nanigasi-san** [comment]
ラズパイでの温湿度センサーの利用について：https://qiita.com/nishiwakki/items/877b10517c26a8a4b583

ラズパイでのI2C通信について：https://www.qoosky.io/techs/2316d68b2e
