### ISSUE TITLE
センシングとコンソール出力のマルチスレッド化

### ISSUE THREAD

**Issue by kantarow** [nanigasi-san/PubSubSensor#2]
1. #1 のコードを改良してマルチスレッド化する  
2. クラスとして書いてファイルを分ける

**Comment by kantarow** [comment]
ネットワークループをバックグラウンドのスレッドで動かすやつがあるぽい  
https://github.com/eclipse/paho.mqtt.python#loop_start--loop_stop

**Comment by nanigasi-san** [comment]
これめっちゃ便利そうだけど、なんか今回は「ROSなどに頼らないマルチスレッドプログラミングを(俺が)できるのか」みたいなのがあるらしいので、exampleくらいに素直に実装してそれをマルチスレッドで動かす、みたいな流れになりそう

**Comment by kantarow** [comment]
よく分からんけどわかった

**Comment by nanigasi-san** [comment]
各センサについてクラスを作ってsetup, readをしていきます

```python
class SensorName:
    def __init__(self, bus):
        self.address = # アドレス
        self.bus = bus
    def setup(self):
        # モード設定などの最初に送るもの
    def read(self):
        # 何か送る必要があったらその処理
        return bus.read___hoge____() # センサーデータ
```

みたいなのを想定しています

**Comment by nanigasi-san** [comment]
どうやらクラス内で非同期処理をしないといけないらしい

**Comment by nanigasi-san** [comment]
https://docs.python.org/ja/3/library/multiprocessing.html#logging

loggerは標準の奴とは分けたほうがいいらしい(衝突するので)
